In [1]:
# TO INSERT IN BETWEEN OF A LIST
# syntax ==> list_name.insert(index_pos,word)

list = ['delhi','bangalore','mumbai','pune']
list.insert(2,'nashik')
print(list)

['delhi', 'bangalore', 'nashik', 'mumbai', 'pune']


In [2]:
#TO REMOVE A CERTAIN INDEX VALUE FROM THE LIST
list.pop(1)
print(list)

['delhi', 'nashik', 'mumbai', 'pune']


.pop is to remove index

.remove is to remove an element of the list

In [3]:
#TO WANT VALUES FROM A CERTAIN INDEX POSITION + 4
print(list[2:2+2])

['mumbai', 'pune']


dictionary mein dict.keys() and dict.values()

del(dict['value'])

In [4]:
name = ['neha','rishin','ragesh','mini','lakshmi']
dic = {}

for i in name:
    dic[i[0]] = i
    
print(dic)
# it didnt print rishin because every value to have a unique key

{'n': 'neha', 'r': 'ragesh', 'm': 'mini', 'l': 'lakshmi'}


In [5]:
details = {'name1' : ['neha',23],
           'name2' : ['ragesh',54],
           'name3' : ['mini',34]}

user_name = input()
password = int(input())

for i in details:
    if((user_name == details[i][0]) and (password == details[i][1])):
        print("successful login")
    else:
        pass

neha 34
34


# NUMPY

In [1]:
import numpy as np

In [7]:
n = np.array([2,3,4,5])
print (n * 3)

[ 6  9 12 15]


if it was merely a list we had to iterate each element in the list and then continue

In [8]:
# numpy is also used for creating dimensional arrays
n2 = np.array([[3,4,5,6,7],[2,4,2,1,6],[7,9,7,2,1]])
print(n2)

[[3 4 5 6 7]
 [2 4 2 1 6]
 [7 9 7 2 1]]


In [9]:
print(np.sum(n2))
print(np.mean(n2))
print(np.min(n2))
print(np.max(n2))
print(np.std(n2))
print(np.argmax(n2))    #index pos of max value
print(np.argmin(n2))    #index pos of min value

66
4.4
1
9
2.4440403706431146
11
8


In [10]:
print(np.shape(n2))
print(np.size(n2))
print(np.ndim(n2))

(3, 5)
15
2


In [11]:
# to access any particular element .....do it just like matrix
print(n2[0][1])

4


In [12]:
#slicing
#syntax ------   array_name[row_starting_index:ending_index, col_start_index:col_ending_index]
n2[0:0+3, 1:1+1]

array([[4],
       [4],
       [9]])

In [13]:
sliced = n2[1:1+2, 1:1+3]

In [14]:
sliced[0,0] = 69
sliced

array([[69,  2,  1],
       [ 9,  7,  2]])

In [15]:
n2

array([[ 3,  4,  5,  6,  7],
       [ 2, 69,  2,  1,  6],
       [ 7,  9,  7,  2,  1]])

In [16]:
random = np.array([[3,4,5,6,7],[2,4,2,1,6],[7,9,7,2,1]])
print(random)

[[3 4 5 6 7]
 [2 4 2 1 6]
 [7 9 7 2 1]]


In [17]:
# if we slice an array and make changes in the sliced portion then the changes will be reflected in the main array
# to avoid that use .copy()
sliced1 =  random[1:1+2, 1:1+3].copy()
sliced1[0,0] = 69
sliced

array([[69,  2,  1],
       [ 9,  7,  2]])

In [18]:
random

array([[3, 4, 5, 6, 7],
       [2, 4, 2, 1, 6],
       [7, 9, 7, 2, 1]])

In [19]:
#array + range = arange
n3 = np.arange(0,36)
n3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [20]:
#reshaping ----- total 36 elements ==> 1*36, 6*6, 9*4
n3.reshape(9,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [21]:
#converting n dimentional array into single dimension
n3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [22]:
arr = np.array([np.arange(0,48)])
arr.reshape(12,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [23]:
print(np.array([[[3,4,5,6,7],[2,4,2,1,6],[7,9,7,2,1]],
       [[3,4,5,6,7],[2,4,2,1,6],[7,9,7,2,1]]]))

[[[3 4 5 6 7]
  [2 4 2 1 6]
  [7 9 7 2 1]]

 [[3 4 5 6 7]
  [2 4 2 1 6]
  [7 9 7 2 1]]]


In [24]:
# MATHEMATICAL FUNCTIONS

arr1 = np.array([[2,3],[4,8]])
arr2 = np.array([[5,10]])

# since arr2 is of dimension 1,2 so we take the transpose 
arr3 = arr2.T

dot = np.dot(arr1,arr3)
dot

#or

print(np.dot(arr1,arr2.T))

[[ 40]
 [100]]


In [25]:
# to take inverse of a matrix

np.linalg.inv(arr1)

array([[ 2.  , -0.75],
       [-1.  ,  0.5 ]])

In [26]:
# to excess row wise use --- axis =1
# to excess col wise use --- axis =0

print(np.sum(n2,axis=1))
print(np.mean(n2,axis=1))
print(np.min(n2,axis=1))
print(np.max(n2,axis=1))
print(np.std(n2,axis=1))
print(np.argmax(n2,axis=1))    #index pos of max value
print(np.argmin(n2,axis=1))    #index pos of min value

[25 80 26]
[ 5.  16.   5.2]
[3 1 1]
[ 7 69  9]
[ 1.41421356 26.55560205  3.12409987]
[4 1 1]
[0 3 4]


In [27]:
# GENERATING AN IDENTITY MATRIX

np.eye(4)
# whatever number you mention inside the bracket becomes the dimension

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
# GENERATING 0 MATRIX

np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
# GENERATING 1 MATRIX

np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2]:
# full function creates a n*n matrix
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# PANDAS

In [30]:
import pandas as pd

In [38]:
df = pd.DataFrame({'name' : ['neha','rishin','ragesh','mini','lakshmi'],
                  'age' : [23,45,67,43,23],
                  'experience' : [2.3,4.6,6.4,8.6,8.5]})
df

name  age  experience
0     neha   23         2.3
1   rishin   45         4.6
2   ragesh   67         6.4
3     mini   43         8.6
4  lakshmi   23         8.5

In [39]:
df.dtypes

name           object
age             int64
experience    float64
dtype: object

In [49]:
# CONVERTING NUMPY TO PANDAS

b = np.array([[2,3,4],[3,4,5]])
pd.DataFrame(b, columns = ['name1','name2','name3'],index = [1,2])
# we just need to pass the numpy array name and give col names if any
# one can change the index as well

pd.DataFrame(b, columns = ['name1','name2','name3'],index = ['a','b'])

name1  name2  name3
a      2      3      4
b      3      4      5

In [50]:
# CONVERTING PANDAS TO NUMPY

print(df.values)

[['neha' 23 2.3]
 ['rishin' 45 4.6]
 ['ragesh' 67 6.4]
 ['mini' 43 8.6]
 ['lakshmi' 23 8.5]]


In [52]:
# TO ACCESS SINGLE COL
df['name']

0       neha
1     rishin
2     ragesh
3       mini
4    lakshmi
Name: name, dtype: object

In [53]:
# ACCESSING MULTIPLE COL
# simply pass the list of cols u want inside the dataframe[]

df[['name','age']]

name  age
0     neha   23
1   rishin   45
2   ragesh   67
3     mini   43
4  lakshmi   23

In [54]:
# ACCESSING A ROW
# the no inside [] represents the row number

df.loc[0]

name          neha
age             23
experience     2.3
Name: 0, dtype: object

In [56]:
# ACCESSING MULTIPLE ROWS
df.loc[[0,3]]

name  age  experience
0  neha   23         2.3
3  mini   43         8.6

In [57]:
# TO access certain rows and cols

df.loc[[1,3], ['name','experience']]

name  experience
1  rishin         4.6
3    mini         8.6

In [60]:
# TO ACCESS THINGS IN CONTINUITY ---just use : and no brackets needed

df.loc[1:3, 'name':'experience']

name  age  experience
1  rishin   45         4.6
2  ragesh   67         6.4
3    mini   43         8.6

In [31]:
df = pd.read_csv('http://bit.ly/kaggletrain')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [32]:
df.shape

(891, 12)

DATA FILTERING

In [33]:
#all survived data samples

In [34]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

# AUTOMOBILE PROJECT

In [35]:
#to check the data types of the values present in a row
for val in df1.loc[0]:
    print(val, type(val))


#here 0 indicates the row number

NameError: name 'df1' is not defined